"""Central Camunda job type constants."""

REGISTER_INVOICE_JOB_TYPE = "register-invoice"
REQUEST_INFO_JOB_TYPE = "request-info"
INFORM_SUPPLIER_REJECTION_JOB_TYPE = "inform-supplier-rejection"
EXECUTE_PAYMENT_JOB_TYPE = "execute-payment"

REGISTER_INVOICE = REGISTER_INVOICE_JOB_TYPE
REQUEST_INFO = REQUEST_INFO_JOB_TYPE
INFORM_SUPPLIER_REJECTION = INFORM_SUPPLIER_REJECTION_JOB_TYPE
EXECUTE_PAYMENT = EXECUTE_PAYMENT_JOB_TYPE

ALL_JOB_TYPES = (
	REGISTER_INVOICE_JOB_TYPE,
	REQUEST_INFO_JOB_TYPE,
	INFORM_SUPPLIER_REJECTION_JOB_TYPE,
	EXECUTE_PAYMENT_JOB_TYPE,
)

JOB_TYPES = ALL_JOB_TYPES

__all__ = [
	"ALL_JOB_TYPES",
	"JOB_TYPES",
	"REGISTER_INVOICE_JOB_TYPE",
	"REQUEST_INFO_JOB_TYPE",
	"INFORM_SUPPLIER_REJECTION_JOB_TYPE",
	"EXECUTE_PAYMENT_JOB_TYPE",
	"REGISTER_INVOICE",
	"REQUEST_INFO",
	"INFORM_SUPPLIER_REJECTION",
	"EXECUTE_PAYMENT",
]
